language: go

go:
- '1.10'

# blech, Travis downloads with capitals in DirectXMan12, which confuses go
go_import_path: github.com/directxman12/k8s-prometheus-adapter

before_install:
- curl -L -s https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -o $GOPATH/bin/dep
- chmod +x $GOPATH/bin/dep

install:
- make -B vendor

script: make verify

cache:
  directories:
  - ~/gopath/pkg/dep/

sudo: required
services:
- docker

deploy:
  provider: script
  script: bash .travis-deploy.sh
  on:
    branch: master