apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.reader.roleBinding.name }}
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.reader.roleBinding.roleRef.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.apiserver.name }}
  namespace: {{ .Values.namespace }}
