apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apiserver.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.apiserver.servicePort }}
    targetPort: {{ .Values.apiserver.containerPort }}
  selector:
    app: {{ .Values.apiserver.name }}
