---
# Source: custom-metrics-prometheus-adapter/templates/custom-metrics-apiserver-service-account.yaml
kind: ServiceAccount
apiVersion: v1
metadata:
  name: custom-metrics-apiserver
  namespace: monitoring

